spring:
  application:
    name: StudentManagementSystem
  datasource:
    url: jdbc:mysql://localhost:3306/student_management_db?createDatabaseIfNotExist=true
    username: root
    password: ""
  jpa:
    show-sql: true